### ISSUE TITLE
Optimize all your pngs with kraken.io

### ISSUE THREAD

**Issue by ingbrzy** [rcset/MIUIAndroid_XML_v5_TH#35]
Optimize all your pngs by https://kraken.io/web-interface (select Lossy conversion).. it will make lighter pngs and faster system... and.. save more space in /system partition... for example in my repo it saved 5MB..  https://github.com/MIUICzech-Slovak/MA-XML-5.0-SLOVAK/commit/6bc1a160369764749d6ec9efe3909b7c4e93031e

**Comment by myfew2542** [comment]
can't use for s4 i9505 miui
