### ISSUE TITLE
Nice work guys..!

### ISSUE THREAD

**Issue by ingbrzy** [rcset/MIUIAndroid_XML_v5_TH#43]
Just checked your xmls and I have to say you did Great job guys...!

just let me know which devices do you have and I will make a test builds for you to check translation if its needed... 

we will release it for public next orange friday 3.10.11...

**Comment by rcset** [comment]
Actually not in your list, I have a mtk local band device with port rom miui5 3.9.27
If you need me to test before release. Please give me a build of zte v987(P188F04)
I can port from it.
Thanks

**Comment by ingbrzy** [comment]
English base ROM
http://caro.miuiandroid.com/3.9.27/miuiandroid_P188F04_jb-3.9.27.zip

Multilang pack
http://caro.miuiandroid.com/3.9.27/miuiandroid_lang_P188F04-3.9.27.zip

**Comment by rcset** [comment]
Tested. Its seems to be complete.
But need to fix some of the translation.
And some words that are not translated.
Thanks

![screenshot_2013-10-08-01-17-11](https://f.cloud.github.com/assets/2105265/1282946/f5d63ee6-2f7c-11e3-9b65-848d78bcb5bc.png)
![screenshot_2013-10-08-01-16-43](https://f.cloud.github.com/assets/2105265/1282947/f998b018-2f7c-11e3-9935-474b4c2c2d11.png)
![screenshot_2013-10-08-01-16-35](https://f.cloud.github.com/assets/2105265/1282948/fc8417b8-2f7c-11e3-9023-2b1f0a2da464.png)

**Comment by ingbrzy** [comment]
great.. thank you... ! btw what time zone are you...?

**Comment by rcset** [comment]
my time zone (Asian/Bangkok)
GMT+07:00
