### ISSUE TITLE
Cannot see Thai text in Miui 3.12.6

### ISSUE THREAD

**Issue by ThankGoodness555** [rcset/MIUIAndroid_XML_v5_TH#50]
Cannot see Thai text in the new V5 rom

Samsung Galaxy S4 IG9500

**Comment by ingbrzy** [comment]
You mean,  there is not a Thai lang in the settings?  Then try set your lang vie app Morelocale2...

**Comment by ThankGoodness555** [comment]
There is no Thai language in the settings and using Morelocale2 to set makes it change into blank space.

Had to copy new fonts with Thai into System/Fonts and set it with Font Installer.

Even then, small Thai fonts like in the app LINE or 10dp thai fonts shows up as small rectangles

**Comment by ingbrzy** [comment]
Are you sure you are using our miuiandroid multilang version? 

Sent from Yahoo Mail on Android

**Comment by ThankGoodness555** [comment]
Yes. And there are many other language options except for Thai

**Comment by ThankGoodness555** [comment]
The other version on the website only has Chinese and English or something like that....

**Comment by ingbrzy** [comment]
try a new version http://xiaomi.eu/community/threads/3-12-6.22985/

**Comment by ThankGoodness555** [comment]
No change in the new version. Took some pictures this time

![photo 300](https://f.cloud.github.com/assets/6110588/1697699/fffc48ec-5ef8-11e3-8e3e-26aa1debf659.jpeg)
![photo 301](https://f.cloud.github.com/assets/6110588/1697700/002ff944-5ef9-11e3-9e46-6b3d28a1fa4d.jpeg)
![photo 302](https://f.cloud.github.com/assets/6110588/1697701/00663efa-5ef9-11e3-99c2-7047d37d310c.jpeg)
![photo 303](https://f.cloud.github.com/assets/6110588/1697702/00919780-5ef9-11e3-9102-1d5c0fd25357.jpeg)
![photo 304](https://f.cloud.github.com/assets/6110588/1697703/00959952-5ef9-11e3-9508-ecc3f70ff2b9.jpeg)
![photo 305](https://f.cloud.github.com/assets/6110588/1697704/009721be-5ef9-11e3-8412-9f087690bb57.jpeg)
![screenshot_2013-12-07-11-23-14](https://f.cloud.github.com/assets/6110588/1697705/009b0fb8-5ef9-11e3-91e4-36767d53d1f9.png)

**Comment by ThankGoodness555** [comment]
![photo 306](https://f.cloud.github.com/assets/6110588/1697727/bd68c192-5efb-11e3-9e79-4e9a816a8b8e.jpeg)
