### ISSUE TITLE
There is no Thai language in ROM

### ISSUE THREAD

**Issue by simon112112** [rcset/MIUIAndroid_XML_v5_TH#54]
The problem is that there is no THAI language in ROM's Xiaomi Redmi Note 4G LTE - Stable 6.0.0 Multilang

I hope next version Put this into the language In agreement with the correct word "Camera" is "กล้องถ่ายรูป".

Thanks for making everything.

**Comment by ingbrzy** [comment]
as you see https://github.com/rcset/MIUIAndroid_XML_v5_TH/commits/master
nobody care about thai translation since 15.03.... so we disabled it for our builds...

**Comment by simon112112** [comment]
In the future there will be or not ?
You do not need to be translated. Put in Thai that has already been translated...

I wanna to have my language, Please.

**Comment by EkachaiMee** [comment]
I hope too because now there is xiaomithailand web site and xiaomi member in thailand still increasing.
Thank you for advance.

**Comment by qoooqo** [comment]
我用的note 4g Android4.4 要用哪个ROM 才可以用泰语MENU？
